# Generated by Django 6.0.2 on 2026-07-17 03:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsandevent', '0002_galleryevent_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, help_text='Hero image for gallery page header', max_length=255, verbose_name='gallery_hero')),
            ],
            options={
                'verbose_name': 'Gallery Setting',
                'verbose_name_plural': 'Gallery Settings',
            },
        ),
    ]
