# Generated by Django 6.0.5 on 2026-07-16 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('chaplain', 'Chaplain'), ('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('pro', 'PRO (Public Relations Officer)'), ('coordinator', 'Coordinator'), ('other', 'Other')], max_length=50)),
                ('parish', models.CharField(blank=True, max_length=255)),
                ('deanery', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tenure', models.CharField(blank=True, help_text="e.g., '2024 - 2026'", max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lay Leader',
                'verbose_name_plural': 'Lay Leaders',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('evangelization', 'Evangelization'), ('social_welfare', 'Social Welfare'), ('youth', 'Youth')], max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('on_hold', 'On Hold')], max_length=20)),
                ('parish', models.CharField(blank=True, max_length=255)),
                ('deanery', models.CharField(blank=True, max_length=255)),
                ('location', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('progress', models.IntegerField(default=0, help_text='0-100 percentage')),
                ('project_lead', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('objectives', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='LayAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('youth', 'Youth'), ('men', 'Men'), ('women', 'Women'), ('apostolate', 'Apostolate'), ('devotional', 'Devotional')], max_length=50)),
                ('description', models.TextField()),
                ('patron_saint', models.CharField(blank=True, max_length=255)),
                ('meeting_schedule', models.TextField(blank=True, help_text="e.g., 'First Sunday of the month at 3 PM'")),
                ('image_url', models.URLField()),
                ('meeting_venue', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('membership_count', models.PositiveIntegerField(blank=True, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('chaplain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaplain_for_associations', to='content.layleader')),
                ('officers', models.ManyToManyField(blank=True, related_name='officer_in_associations', to='content.layleader')),
            ],
            options={
                'verbose_name': 'Lay Association',
                'verbose_name_plural': 'Lay Associations',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
