# Generated by Django 6.0.5 on 2026-07-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('bishop', 'Bishop'), ('vicar_general', 'Vicar General'), ('parish_priest', 'Parish Priest'), ('assistant_priest', 'Assistant Priest'), ('chaplain', 'Chaplain'), ('deacon', 'Deacon')], max_length=30)),
                ('parish', models.CharField(blank=True, help_text='Parish name or assignment', max_length=255)),
                ('deanery', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('ordained_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Priest',
                'verbose_name_plural': 'Priests',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
