# Generated by Django 6.0.5 on 2026-07-17 00:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bishop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priest',
            name='image_url',
        ),
        migrations.AddField(
            model_name='priest',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
