# Generated by Django 6.0.2 on 2026-07-17 00:58

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishop', '0002_remove_priest_image_url_priest_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatOfArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Coat of Arms', max_length=255)),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='hero_image')),
                ('coat_of_arm_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='coat_of_arm_image')),
                ('description', models.TextField(blank=True, help_text='General description of the coat of arms')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Coat of Arms',
                'verbose_name_plural': 'Coat of Arms',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='LocalOrdinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Local Ordinary', max_length=255)),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='hero_image')),
                ('bishop_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='bishop_image')),
                ('text', models.TextField(help_text='Biography and information about the Local Ordinary')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Local Ordinary',
                'verbose_name_plural': 'Local Ordinaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoatOfArmItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('coat_of_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bishop.coatofarm')),
            ],
            options={
                'verbose_name': 'Coat of Arm Item',
                'verbose_name_plural': 'Coat of Arm Items',
                'ordering': ['coat_of_arm', 'display_order'],
            },
        ),
    ]
