# Generated by Django 6.0.2 on 2026-07-17 01:04

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bishop', '0003_coatofarm_localordinary_coatofarmitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BishopMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.CharField(max_length=500)),
                ('full_message', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(default="Bishop's Message", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bishop Message',
                'verbose_name_plural': 'Bishop Messages',
                'ordering': ['-date', '-display_order'],
            },
        ),
    ]
