# Generated by Django 6.0.5 on 2026-07-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(default='', upload_to='heroes/'),
        ),
    ]
