# Generated by Django 6.0.5 on 2026-07-16 23:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_hero_cta_label_remove_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
