# Generated by Django 6.0.5 on 2026-07-17 00:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deanery',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='discovermessage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='greeting',
            name='bishop_image_url',
        ),
        migrations.RemoveField(
            model_name='parish',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='recentnews',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='recentsermon',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='upcomingevent',
            name='image_url',
        ),
        migrations.AddField(
            model_name='deanery',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='discovermessage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='greeting',
            name='bishop_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='bishop_image'),
        ),
        migrations.AddField(
            model_name='parish',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='recentnews',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='recentsermon',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
