# Generated by Django 6.0.5 on 2026-07-16 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category_key', models.SlugField(help_text="URL-friendly key (e.g., 'education')", unique=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Institution Category',
                'verbose_name_plural': 'Institution Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hero_image_url', models.URLField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='institution.institutioncategory')),
            ],
            options={
                'verbose_name': 'Institution Subcategory',
                'verbose_name_plural': 'Institution Subcategories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('principal_name', models.CharField(blank=True, help_text='Principal/Director name', max_length=255)),
                ('principal_title', models.CharField(blank=True, default='Principal', max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('staff_count', models.PositiveIntegerField(blank=True, null=True)),
                ('student_count', models.PositiveIntegerField(blank=True, null=True)),
                ('operating_hours', models.CharField(blank=True, help_text="e.g., '8:00 AM - 4:00 PM'", max_length=255)),
                ('mission_statement', models.TextField(blank=True)),
                ('facilities', models.TextField(blank=True, help_text='Comma-separated list of facilities')),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='institution.institutionsubcategory')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
